Add Home page
yash9263/ecom-html pull request #1
Opened 2022-02-16 18:45 UTC by yash9263

2022-02-16 18:52 UTC, iambizan approved these changes

2022-02-16 19:16 UTC, hsnice16 approved these changes
The code looks good, added a few suggestions. And one more suggestion on the UI, as I understand these are links (in the img) so you can give some property to distinguish them on hover. Right now only the cursor is changing to a pointer. 
![image](https://user-images.githubusercontent.com/56081584/154338833-4156c437-807f-46ec-bf88-3ff542db6655.png)

BTW, great work on the UI.

2022-02-16 19:16 UTC, hsnice16 commented on styles/pages/home.css
> +  padding: 64px 32px 32px;
I think you are maintaining padding at the multiple of 8. Even, if you are maintaining that, I think, these are some big values in `px` so you can convert them into `rem` and then can maintain the jump of `0.5rem` or `1rem`, as you like.

2022-02-16 19:16 UTC, hsnice16 commented on index.html
> +            src="https://res.cloudinary.com/yashwant9263/image/upload/v1644670094/Camp/ecommerce/home/Equipments_hl1qar.jpg"
you can use the `alt` and `loading=lazy` attributes with `img`. To improve their performance, and increase reachability.

2022-02-16 19:21 UTC, MayankKumar10 approved these changes
Everything Looks good you can merge it

2022-02-16 19:21 UTC, MayankKumar10 commented on index.html
> +          <img
add alt tag in img

2022-02-16 19:21 UTC, MayankKumar10 commented on styles/pages/home.css
> +  max-width: 1024px;
don't use px use rem or %

2022-02-16 19:21 UTC, yash9263 commented on styles/pages/home.css
> +  padding: 64px 32px 32px;
I don't want the padding to increase as my font-size increases that's why sticking with px instead of rems

2022-02-16 19:22 UTC, yash9263 commented on index.html
> +            src="https://res.cloudinary.com/yashwant9263/image/upload/v1644670094/Camp/ecommerce/home/Equipments_hl1qar.jpg"
will add alt and loading attributes

2022-02-16 19:22 UTC, yash9263 commented on index.html
> +          <img
will add it

2022-02-16 19:25 UTC, yash9263 commented
@hsnice16 Thanks for the suggestion for the nav will update it.

2022-02-16 19:44 UTC, yash9263 commented on index.html
> +            src="https://res.cloudinary.com/yashwant9263/image/upload/v1644670094/Camp/ecommerce/home/Equipments_hl1qar.jpg"
updated both attributes

2022-02-16 19:45 UTC, yash9263 commented on index.html
> +          <img
added alt tag

2022-02-16 20:21 UTC, hsnice16 commented on styles/pages/home.css
> +  padding: 64px 32px 32px;
As, there is no media query, so I assume that they are for big screens. And if they are for big screens, then don't you think that this padding will be more on smaller devices and you will need to reduce them using media query. 

And if you have to reduce them on smaller devices, then rem would be good, I guess.

2022-02-17 02:41 UTC, govindappaarun commented on index.html
> +    <main class="main-cont">
avoid these shortcut class names, it is not clear has to container or content?

2022-02-17 03:00 UTC, govindappaarun requested changes
I have not gone in detail, but could find few things to take care.  
improve on the class naming a bit and removing unused props

2022-02-17 05:38 UTC, yash9263 commented on styles/pages/home.css
> +  right: 0;
the `bottom` is required left and right just to be more specific but will remove those two.

2022-02-17 05:39 UTC, yash9263 commented on styles/pages/home.css
> +  text-align: center;
will remove it

2022-02-17 05:55 UTC, yash9263 commented on styles/pages/home.css
> +  padding: 64px 32px 32px;
I don't think padding will be more for small screens in this case cause on bigger screens 1 software pixel equals 1 hardware pixel CSS states only software pixels but in the case of mobile devices 1 software pixel can be equal to 2 or 3 hardware pixels depending on the device's resolution and dpi. so on mobile, it will not be actually 64px of hardware pixels it will be `64 / 3 = 21.3` if the 1 software pixel is mapped to 3 hardware pixels. So specific to this case it won't be necessary. <br/>
I am not sure how rem will help here? Would like to know if you can show me.

2022-02-17 05:56 UTC, yash9263 commented on index.html
> +    <main class="main-cont">
will update it

2022-02-17 06:53 UTC, hsnice16 commented on styles/pages/home.css
> +  padding: 64px 32px 32px;
Thanks, @yash9263 for sharing this knowledge. I never thought from this angle. Great work.

2022-02-17 08:14 UTC, gauravsinhaweb approved these changes
Nice work!, UI looks clean and soothing. Good to merge after changes.

2022-02-17 08:14 UTC, gauravsinhaweb commented on index.html
> +        <a class="small-text">Legal & Privacy</a>
use li 'list tag' here.

2022-02-17 08:14 UTC, gauravsinhaweb commented on styles/pages/home.css
> +.socials-links {
socials-links isn't correct grammatically instead you can use `social-links` and for the child `social-link`.

2022-02-17 08:37 UTC, MayankKumar10 commented on index.html
> +          <img
Okay, great

2022-02-17 17:56 UTC, merged