Add cart page
yash9263/ecom-html pull request #3
Opened 2022-02-19 18:16 UTC by yash9263

2022-02-19 18:22 UTC, iambizan approved these changes

2022-02-19 18:27 UTC, gauravsinhaweb approved these changes
UI looks good, the shopping card in the card could have some distinguish border. Good to merge after changes.

2022-02-19 18:27 UTC, gauravsinhaweb commented on styles/pages/cart.css
> +  outline: 0;
give outline some value for accessibility.

2022-02-19 18:29 UTC, manojsarna requested changes
Overall Looks Fine

Do check the comments

2022-02-19 18:29 UTC, manojsarna commented on styles/pages/cart.css
> +  display: grid;
you could have used px values!!

2022-02-19 18:29 UTC, manojsarna commented on styles/pages/cart.css
> +}
check here too!!

2022-02-19 18:29 UTC, manojsarna commented on styles/pages/cart.css
> +    grid-template-columns: 1fr;
here also

2022-02-19 18:29 UTC, manojsarna commented on styles/pages/cart.css
> +
used px values!! please check

2022-02-19 18:29 UTC, manojsarna commented on styles/pages/cart.css
> +}
here too

2022-02-19 18:29 UTC, manojsarna commented on styles/pages/cart.css
> +  font-size: 0.9rem;
check for px values

2022-02-19 18:29 UTC, manojsarna commented on styles/pages/cart.css
> +.product-quantity input {
can you elaborate on why so much px values in the css!!

2022-02-19 18:48 UTC, yash9263 commented on styles/pages/cart.css
> +.product-quantity input {
cause I don't want the padding and margin to increase as the font-size increases that's why

2022-02-19 18:49 UTC, yash9263 commented on styles/pages/cart.css
> +  outline: 0;
yep will do that

2022-02-19 19:08 UTC, manojsarna approved these changes
As per the usage of your code.

Seems Superb to me

UI is fantabulous , Yash

you can merge it :)

2022-02-20 11:18 UTC, varun13169 approved these changes
Nit Comments, can be addressed as a follow-up

2022-02-20 11:18 UTC, varun13169 commented on styles/pages/cart.css
> +  padding: 12px;
usage of px

2022-02-20 16:12 UTC, merged